version: '3.9'

services:
  bot:
    container_name: bot
    hostname: bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    restart: always
