"""empty message

Revision ID: 16dca5b5758c
Revises: 
Create Date: 2023-12-12 23:16:34.508116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dca5b5758c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('manga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('manga_id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('manga_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.manga_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_manga',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('manga', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga'], ['manga.manga_id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user', 'manga')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_manga')
    op.drop_table('manga_updates')
    op.drop_table('users')
    op.drop_table('manga')
    # ### end Alembic commands ###
