"""Init

Revision ID: cbf48a663905
Revises: 
Create Date: 2023-12-11 22:35:31.422620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf48a663905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('manga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('manga_id')
    )
    op.create_table('manga_updates',
    sa.Column('update_manga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.manga_id'], ),
    sa.PrimaryKeyConstraint('update_manga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manga_updates')
    op.drop_table('manga')
    # ### end Alembic commands ###
